env:
  global:
    - CC_TEST_REPORTER_ID=abc6e07c4b99506e38eb1d4296e3ecf26a386bdcd218237eefab1a0ea770ac6d
    - secure: InYzxNUQC4eszpw3Udj/7kkJiGlIMF7ZbOMc4gFqA7I6/qqaF66ig/i7mZw6GU2avfQwjcD1YrCUI4Q/2DbEAxcxIysLtQgQGoO0c8tOTL5KM/MkV3MRuz5P4P34PKWh4gtHOUA/Rj4fsG9B2hiRtE8fA10fnpCQJWK0H1xjRMmWDpyRP3gnIYqfeAH7IdShy6XORM9FnHn2MbCeT2SF9NZVhsZRdFUlQ4UIv6P4IzA+Ab1rC3xGXoGvu4/GuzbYBoJOgEBx54L1nWUwgpioGlgbTjaSI+o9QL/mofZ9KWCYcZZrvvsXD7mRWieEphSlT+YPD8PrK4nj1HOuEFClVDXjXLXrR+VDJtPfq+RBuodvXUBDTojP/ppTpWixjJwtVaufVhDDtBjviD0W9eWOeKv19SHAnV1m+g1yVfJZ9TEW0dvgiQQxkAwPl2EBoXd79Si+Ct5Eg5APi3hgkijblMeg+iRlhWSdMpNAbU2fb2KzULkuhnY8colE3lgNy28qDFlaN/N+8beOR1kStxTuCwarWGci3QZXkmOWkmR5E23iLQ3pBqsIzgR0dZqP39AK3ONP3kUTrWwhVTXDdW0LqxtheUNN/FWz4lme60gtmUywCUHgVvgFL6B7TIHDGIjgy2iEZP0Apv8MtGxFgQZ6iSWNF9eH5teZpT7gPWabShc=
    - secure: fs3nODYW750t0ADVi1jD/sQg5tKe1NBeWXHbvapRGfETWpsJ5TM/uqel/DU5Te/B+odG7jm8ol038e1xLwkrq2oBOEY61w4qlyuo8XxPH1qjkvvSEZSuU/u/sWro5ETA8gED4CAXFR1bHehjypn1w3L5vFJr4GMdpIfgFtZHuMLRD3LxV9mrrSU87/dbshgnzSvqLs8kB5cMRe5ijfhvvictTiu+IJZMVFw3bOAd8LnI0iQmgpokuu0n83SIFpV/VfHIWvgQ87L7XJfdzDijG6xJVOy89yR1CtEWNFahaoeVoLjpGkGIW07ZVFGwnmU6al2N/YBNUbw7mow8z7xR3iL/ljNacq91ye9maJyiCcoczxNEMef+vMBWpYCSRz8fE43LwOVKxufM3QzN1jFwd5PQb5xFe7wADknW7KseewvWHM7pBPYkvLuXXeEZUc06mEBbrffSnLiLgY5q8sVufkFt233xnAMGlqBjd3841K/HJ8g7bhqn5jfbZSaNxra6gh4wFa1Sdz0qYP/CDczsp8bROHVN76znjY9yPwSrxQijqpZCSEokggWoTy9W78QPtBf9emdxKBEkl1CJGSpLpCAd+BdJcj7ycUmluBQ2BZ5YP4+QdBCJG97RE/ctP5Hof06miK01IZ0n42efvt91IdFyO7/9ndJuqxKd1zxMnzM=
    - secure: vkzO7zQSwNVqX1Kq//2J3KWyG6OGmzLYOQzIGwap69vilvR1l/ULPtFrytBUZPNFrx2+NMU6luHNwKtk8I/5oeIdjWexsZAQrQx9EkLdyR7CjKYPOy20QsDbWc/d8lWn27Ufw+i2JlWIwCLaRnc7ZXmpKydT8BmwZaXqVIZ6gEGUOBi/h4/Sx+5Y46W4Mv+BZXW2ViyeyRgdEObWiRCIywcN0GNV0csWgYmazvGaFDLTTDNX4FV2ySzpuEgt40he10ySaqsw121FGyHaxHrMv6gMUHOnWvdYcTHgsBW6OGgTCkpkgIfcpqZR3Z+2diSVN0TFmbvaP1kEHbh0OqLutH0DlYD8x6YnGyEZU6l41qMtCLsvVc5mSed6mKRFF/vacUYSqAx8O+nzlGnQxuTTEFKkQ3jPBBi+T0rl4s0sGEsG/NUCt+duNdgD2qd31aZENh4Tl1wlEdFY0yGoAPdvW2U9Sz6plS4ce/3czrYCADuLGXWZjSIOQ6ff2OM5J9U3RUDo4s7x3NGHEoobXGAIBM5rqLf72nGwAO55csni264nn5u2Q1v+yeZrd3bK+Hx9sI6W7Y3ranfdWqumSW4u4e7BLIdeFioYMwbJynSDK+W8K6P9CzcId/Je8GZVxwZUxLpJaUE2gMmnmR99C2NCN2mva/6/m3uaymdcdYEPs2M=
language: node_js
node_js:
  - 9
cache: yarn
before_install:
  - chmod +x ./aws_credentials.sh
  - ./aws_credentials.sh
  - sudo apt-get install imagemagick -y
  - yarn global add jest
  - yarn global add codecov
install:
  - yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn clean
  - yarn test
  - codecov
after_script:
  - ./cc-test-reporter upload-coverage < coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
